<!DOCTYPE html>
<html>
	<head>
    	<title>
        	<?php
			
				wp_title( '-', true, 'right' );
				
				//bloginfo( 'name' );
        	?>
        </title>
        <meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' /> 
        <link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">   
		<!-- Generated by IcoMoon.io -->
		<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    	<?php wp_head(); ?>
    </head>
        <body>

            <!--Navbar-->
            <div class="navbar mainHeader">
         
                <div class="container">
                <!--
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                 -->        
                        <a class="navbar-brand" href="http://abstraks.com/"><img src="./wp-content/themes/wpabstraks/assets/logo.png" img border="0" alt="Abstraks logo" /></a>       
                        <div class="collapse navbar-collapse">
                                           
                            <div class="search">
                                <?php dynamic_sidebar( header_search ); ?>
                            </div>
                            <ul class="main-nav">
                                <?php
                            
                                $args = array(
                                        'menu' => 'main-menu',
                                        'echo' => false
                                );
                                
                                echo strip_tags(wp_nav_menu( $args ), '<a>');
                            
                                ?>
                            </ul>
                            
                        </div>                
                </div>
            </div>
            <!--End Navbar-->
                    
           